/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minutes;

public class App {

    public static void main(String[] args) {
        MotorBike ducati = new MotorBike();
        MotorBike bmw = new MotorBike();

        ducati.start();
        bmw.start();

        ducati.setSpeed(150);
        bmw.setSpeed(160);

        System.out.println("Speed of the Ducati " + ducati.getSpeed());
        System.out.println( "Speed of the BMW " + bmw.getSpeed());

        ducati.increaseSpeed();
        bmw.increaseSpeed();

        System.out.println("Speed of the Ducati " + ducati.getSpeed());
        System.out.println( "Speed of the BMW " + bmw.getSpeed());
       

        ducati.stop();
        bmw.stop();

        MotorBike honda = new MotorBike(125);

       System.out.println("Speed of the Honda " + honda.getSpeed());
    }
}
