/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minutes;

public class App {

    public static void main(String[] args) {
        MotorBike ducati = new MotorBike();
        MotorBike bmw = new MotorBike();

        ducati.start();
        bmw.start();

        ducati.speed  = 100;
        bmw.speed  = 150;

        System.out.println("Speed of the Ducati" + ducati.getSpeed());
        System.out.println( "Speed of the BMW" + bmw.getSpeed());
       

        ducati.stop();
        bmw.stop();
    }
}
